{% set name = "lttng-ust" %}
{% set version = "2.13.8" %}

package:
  name: lttng-ust
  version: {{ version }}

source:
  - url: http://lttng.org/files/lttng-ust/lttng-ust-{{ version }}.tar.bz2
    sha256: d4ef98dab9a37ad4f524ccafdfd50af4f266039b528dd5afabce78e49024d937

build:
  skip: true  # [not linux]
  number: 0
  run_exports:
    - '{{ pin_subpackage(name, max_pin="x.x") }}'

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ cdt('numactl') }}
    - make
    - pkg-config
  host:
    - liburcu
  run:
    - liburcu

test:
  commands:
    - test -e $PREFIX/include/lttng/tracepoint.h
    - test -e $PREFIX/lib/liblttng-ust.so

about:
  home: https://lttng.org/
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE
  summary: The LTTng User Space Tracing (LTTng-UST) library allows any C/C++ application to be instrumented for and traced by LTTng.
  doc_url: https://lttng.org/docs/v{{ version }}/
  dev_url: https://github.com/lttng/lttng-ust

extra:
  recipe-maintainers:
    - ZimmerA
    - wolfv
